baseURL = 'https://scholz.ruhr/'
languageCode = 'en-us'
title = 'scholz.ruhr'
theme = 'scholz.ruhr-theme'

[menu]
    [[menu.main]]
        name = 'Home'
        pageRef = '/'
        weight = 10
    [[menu.main]]
        name = 'Blog'
        pageRef = '/blog'
        weight = 20
    [[menu.main]]
        name = 'About'
        pageRef = '/about'
        weight = 30