[build]
  command = "hugo --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.113.0"

[[redirects]]
    from = "/wp-login.php"
    to = "https://speed.hetzner.de/10GB.bin"

[[redirects]]
    from = "/xing"
    to = "https://www.xing.com/profile/Merlin_Scholz4"

[[redirects]]
    from = "/post/*"
    to = "/blog/:splat"
  
[[redirects]]
  from = "/rss"
  to = "/feed.atom"

[[redirects]]
  from = "/index.xml"
  to = "/feed.atom"

[[headers]]
  for = "*.atom"
  [headers.values]
    Content-Type = "application/atom+xml; charset=UTF-8"